name: CI with Dependency Caching

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test-with-cache:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Cache dependencies
      uses: actions/cache@v4
      id: cache-deps
      with:
        path: |
          ~/.cache/pip
          **/__pycache__
        key: cache-4356b84-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          cache-4356b84-${{ runner.os }}-
          cache-4356b84-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Create a requirements file if it doesn't exist
        if [ ! -f requirements.txt ]; then
          echo "requests==2.31.0" > requirements.txt
          echo "numpy==1.24.3" >> requirements.txt
          echo "pandas==2.0.3" >> requirements.txt
        fi
        pip install -r requirements.txt
    
    - name: prime-cache-4356b84
      run: |
        if [ "${{ steps.cache-deps.outputs.cache-hit }}" == 'true' ]; then
          echo "Cache hit! Dependencies restored from cache."
          echo "Cache key: cache-4356b84"
        else
          echo "Cache miss! Installing dependencies fresh."
          echo "Priming cache with key: cache-4356b84"
        fi
        echo "Cache hit: ${{ steps.cache-deps.outputs.cache-hit }}"
    
    - name: Run tests
      run: |
        echo "Running tests with cached dependencies..."
        python -c "import requests, numpy, pandas; print('All dependencies loaded successfully!')"